import {
  Briefcase,
  Car,
  Hammer,
  HeartPulse,
  Music,
  Scissors,
  ShoppingBag,
  Utensils,
  BookOpen,
  Users,
  Sparkles,
  GraduationCap,
  Home,
  Wrench,
  Camera,
  Plane,
  Laptop,
  Baby,
  PawPrint,
  Dumbbell,
  UtensilsCrossed,
  PartyPopper,
  Shirt,
  Building,
  type LucideIcon,
} from "lucide-react";

export const ICON_KEYS = [
  "utensils",
  "utensils-crossed",
  "briefcase",
  "hammer",
  "car",
  "music",
  "heart-pulse",
  "scissors",
  "shopping-bag",
  "book-open",
  "users",
  "sparkles",
  "graduation-cap",
  "home",
  "wrench",
  "camera",
  "plane",
  "laptop",
  "baby",
  "paw-print",
  "dumbbell",
  "party-popper",
  "shirt",
  "building",
] as const;
export type IconKey = (typeof ICON_KEYS)[number];

export const ICON_MAP: Record<IconKey, LucideIcon> = {
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  briefcase: Briefcase,
  hammer: Hammer,
  car: Car,
  music: Music,
  "heart-pulse": HeartPulse,
  scissors: Scissors,
  "shopping-bag": ShoppingBag,
  "book-open": BookOpen,
  users: Users,
  sparkles: Sparkles,
  "graduation-cap": GraduationCap,
  home: Home,
  wrench: Wrench,
  camera: Camera,
  plane: Plane,
  laptop: Laptop,
  baby: Baby,
  "paw-print": PawPrint,
  dumbbell: Dumbbell,
  "party-popper": PartyPopper,
  shirt: Shirt,
  building: Building,
};

export const COLOR_KEYS = [
  "orange",
  "blue",
  "yellow",
  "slate",
  "purple",
  "red",
  "pink",
  "teal",
  "indigo",
  "rose",
  "emerald",
  "green",
  "cyan",
  "sky",
  "violet",
  "amber",
  "lime",
  "fuchsia",
] as const;
export type ColorKey = (typeof COLOR_KEYS)[number];

export const COLOR_MAP: Record<ColorKey, { text: string; bg: string }> = {
  orange: { text: "text-orange-600", bg: "bg-orange-50" },
  blue: { text: "text-blue-600", bg: "bg-blue-50" },
  yellow: { text: "text-yellow-600", bg: "bg-yellow-50" },
  slate: { text: "text-slate-600", bg: "bg-slate-100" },
  purple: { text: "text-purple-600", bg: "bg-purple-50" },
  red: { text: "text-red-600", bg: "bg-red-50" },
  pink: { text: "text-pink-600", bg: "bg-pink-50" },
  teal: { text: "text-teal-600", bg: "bg-teal-50" },
  indigo: { text: "text-indigo-600", bg: "bg-indigo-50" },
  rose: { text: "text-rose-600", bg: "bg-rose-50" },
  emerald: { text: "text-emerald-600", bg: "bg-emerald-50" },
  green: { text: "text-green-600", bg: "bg-green-50" },
  cyan: { text: "text-cyan-600", bg: "bg-cyan-50" },
  sky: { text: "text-sky-600", bg: "bg-sky-50" },
  violet: { text: "text-violet-600", bg: "bg-violet-50" },
  amber: { text: "text-amber-600", bg: "bg-amber-50" },
  lime: { text: "text-lime-600", bg: "bg-lime-50" },
  fuchsia: { text: "text-fuchsia-600", bg: "bg-fuchsia-50" },
};

export function getIcon(key: string): LucideIcon {
  return ICON_MAP[(ICON_KEYS as readonly string[]).includes(key) ? (key as IconKey) : "briefcase"];
}
export function getColor(key: string): { text: string; bg: string } {
  return COLOR_MAP[(COLOR_KEYS as readonly string[]).includes(key) ? (key as ColorKey) : "slate"];
}
