/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUpgradeRouteImport } from './routes/dashboard.upgrade'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardGalleryRouteImport } from './routes/dashboard.gallery'
import { Route as DashboardCouponsRouteImport } from './routes/dashboard.coupons'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUpgradeRoute = DashboardUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGalleryRoute = DashboardGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCouponsRoute = DashboardCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/coupons': typeof DashboardCouponsRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/coupons': typeof DashboardCouponsRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/coupons': typeof DashboardCouponsRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/cadastro'
    | '/contato'
    | '/dashboard'
    | '/directory'
    | '/login'
    | '/planos'
    | '/sitemap.xml'
    | '/sobre'
    | '/blog/$slug'
    | '/business/$slug'
    | '/dashboard/analytics'
    | '/dashboard/coupons'
    | '/dashboard/gallery'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/upgrade'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/cadastro'
    | '/contato'
    | '/directory'
    | '/login'
    | '/planos'
    | '/sitemap.xml'
    | '/sobre'
    | '/blog/$slug'
    | '/business/$slug'
    | '/dashboard/analytics'
    | '/dashboard/coupons'
    | '/dashboard/gallery'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/upgrade'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/cadastro'
    | '/contato'
    | '/dashboard'
    | '/directory'
    | '/login'
    | '/planos'
    | '/sitemap.xml'
    | '/sobre'
    | '/blog/$slug'
    | '/business/$slug'
    | '/dashboard/analytics'
    | '/dashboard/coupons'
    | '/dashboard/gallery'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/upgrade'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DirectoryRoute: typeof DirectoryRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upgrade': {
      id: '/dashboard/upgrade'
      path: '/upgrade'
      fullPath: '/dashboard/upgrade'
      preLoaderRoute: typeof DashboardUpgradeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery': {
      id: '/dashboard/gallery'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof DashboardGalleryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/coupons': {
      id: '/dashboard/coupons'
      path: '/coupons'
      fullPath: '/dashboard/coupons'
      preLoaderRoute: typeof DashboardCouponsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCouponsRoute: typeof DashboardCouponsRoute
  DashboardGalleryRoute: typeof DashboardGalleryRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUpgradeRoute: typeof DashboardUpgradeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCouponsRoute: DashboardCouponsRoute,
  DashboardGalleryRoute: DashboardGalleryRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUpgradeRoute: DashboardUpgradeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DirectoryRoute: DirectoryRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  BusinessSlugRoute: BusinessSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
