/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardUpgradeRouteImport } from './routes/dashboard.upgrade'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardGalleryRouteImport } from './routes/dashboard.gallery'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardCouponsRouteImport } from './routes/dashboard.coupons'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth.accept-invite'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'
import { Route as AdminManagersRouteImport } from './routes/admin.managers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBusinessesRouteImport } from './routes/admin.businesses'
import { Route as AdminAccountRouteImport } from './routes/admin.account'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardUpgradeRoute = DashboardUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGalleryRoute = DashboardGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCouponsRoute = DashboardCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManagersRoute = AdminManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/terms': typeof TermsRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/managers': typeof AdminManagersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/coupons': typeof DashboardCouponsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/terms': typeof TermsRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/managers': typeof AdminManagersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/coupons': typeof DashboardCouponsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/terms': typeof TermsRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/managers': typeof AdminManagersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/coupons': typeof DashboardCouponsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/cadastro'
    | '/contato'
    | '/dashboard'
    | '/directory'
    | '/login'
    | '/planos'
    | '/privacy'
    | '/sitemap.xml'
    | '/sobre'
    | '/terms'
    | '/admin/account'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/managers'
    | '/admin/waitlist'
    | '/auth/accept-invite'
    | '/auth/confirm'
    | '/blog/$slug'
    | '/business/$slug'
    | '/dashboard/analytics'
    | '/dashboard/coupons'
    | '/dashboard/events'
    | '/dashboard/gallery'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/upgrade'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/cadastro'
    | '/contato'
    | '/directory'
    | '/login'
    | '/planos'
    | '/privacy'
    | '/sitemap.xml'
    | '/sobre'
    | '/terms'
    | '/admin/account'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/managers'
    | '/admin/waitlist'
    | '/auth/accept-invite'
    | '/auth/confirm'
    | '/blog/$slug'
    | '/business/$slug'
    | '/dashboard/analytics'
    | '/dashboard/coupons'
    | '/dashboard/events'
    | '/dashboard/gallery'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/upgrade'
    | '/admin'
    | '/dashboard'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/cadastro'
    | '/contato'
    | '/dashboard'
    | '/directory'
    | '/login'
    | '/planos'
    | '/privacy'
    | '/sitemap.xml'
    | '/sobre'
    | '/terms'
    | '/admin/account'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/managers'
    | '/admin/waitlist'
    | '/auth/accept-invite'
    | '/auth/confirm'
    | '/blog/$slug'
    | '/business/$slug'
    | '/dashboard/analytics'
    | '/dashboard/coupons'
    | '/dashboard/events'
    | '/dashboard/gallery'
    | '/dashboard/leads'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/upgrade'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DirectoryRoute: typeof DirectoryRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermsRoute: typeof TermsRoute
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/upgrade': {
      id: '/dashboard/upgrade'
      path: '/upgrade'
      fullPath: '/dashboard/upgrade'
      preLoaderRoute: typeof DashboardUpgradeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery': {
      id: '/dashboard/gallery'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof DashboardGalleryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/coupons': {
      id: '/dashboard/coupons'
      path: '/coupons'
      fullPath: '/dashboard/coupons'
      preLoaderRoute: typeof DashboardCouponsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/managers': {
      id: '/admin/managers'
      path: '/managers'
      fullPath: '/admin/managers'
      preLoaderRoute: typeof AdminManagersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminManagersRoute: typeof AdminManagersRoute
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminManagersRoute: AdminManagersRoute,
  AdminWaitlistRoute: AdminWaitlistRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCouponsRoute: typeof DashboardCouponsRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardGalleryRoute: typeof DashboardGalleryRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUpgradeRoute: typeof DashboardUpgradeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCouponsRoute: DashboardCouponsRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardGalleryRoute: DashboardGalleryRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUpgradeRoute: DashboardUpgradeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DirectoryRoute: DirectoryRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermsRoute: TermsRoute,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  BusinessSlugRoute: BusinessSlugRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
